### ISSUE TITLE
How to style navigation links (in order to implement a responsive grid)?

### ISSUE THREAD

**Issue by westurner** [maranget/hevea#10]
How should I add a `<div>` around the navigation links?

Currently, the navigation links from ``\linkstext``/`\setlinkstext` output to HTML like this:

```html
<body >
<a href="thinkstats2001.html"><img src="" alt="Previous" class="navarrow prevarrow"></a>
<a href="index.html"><img src="" alt="Up" class="navarrow uparrow"></a>
<a href="thinkstats2003.html"><img src="" alt="Next" class="navarrow nextarrow"></a>
<hr>
```

Instead, in order to style them correctly, use a responsive grid, and include `role=navigation` for screen readers, I would like to do something like the following:

```html
<body >
<div class="navarrows" role="navigation"><ul>
 <li><a class="navarrow" href="thinkstats2001.html" title="Previous">Previous 🡄</a></li>
 <li><a class="navarrow" href="index.html" title="Up">Up 🡅</a></li>
 <li><a class="navarrow" href="thinkstats2003.html" title="Next">Next 🡆</a></li>
</ul></div>
```
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role

I've tried this, which somewhat works, but (1) there doesn't seem to be a good way to style the outer `<a>` with e.g. `{text-decoration:none}` and (2) I need to wrap these in a `<div>` in order to include the navlinks in the responsive grid:

```latex
\setlinkstext
  {\imgsrc[alt="Previous" class="navarrow prevarrow"]{}}
  {\imgsrc[alt="Up" class="navarrow uparrow"]{}}
  {\imgsrc[alt="Next" class="navarrow nextarrow"]{}} 
```

I am not at all well-versed in LaTex. So,
in a `macros.hva`, I've tried various permutations of this with no success:

```latex
% NAVIGATION LINKS
\let\oldsetlinkstext=\setlinkstext
% \newcommand{\setlinkstext}[3]
\renewcommand{\setlinkstext}[3]{%
\begin{rawhtml}
<div class="navarrows">
\end{rawhtml}
\oldsetlinkstext{#1}{#2}{#3}
\begin{rawhtml}
</div>
\end{rawhtml}}
```

From html/hevea.hva:

```latex
\newsavebox{\@linkstext}
\newcommand{\setlinkstext}[3]
  {\sbox{\@linkstext}
    {\@printnostyle{<!--SETENV }%
    \@link@arg{PREVTXT}{#1}%
    \@link@arg{UPTXT}{#2}%
    \@link@arg{NEXTTXT}{#3}%
    \@printnostyle{-->
}}}
```

Also, I'll share what I have so far for a responsive CSS grid that works on mobile in a comment.

**Comment by westurner** [comment]
`header.html`:

```html
<div id="main">
  <div id="colorbar"></div>
  <div id="content">
```

`footer.html`:

```html
  </div>
  <div id="sidebar">
  <!-- ... -->
  </div>
</div>
</body>
```

`custom.css`:

```css

pre.verbatim {
    overflow-x: auto;
    max-width: 100%;
}
div#main {
    display: grid;
    grid-template-columns: 1fr;
    grid-auto-rows: minmax(100px, auto);
    grid-gap: 10px;
    gap: 10px;
}
div#colorbar {
    display: none;
    background: #DC143C;
}
div#content {
    min-width: 0;
}
div#content p:first-of-type {
    margin-top: 0;
}
h1, h2, h3, h4, h5, h6 {
    margin: 0;
}
img {
    max-width: 100%
}
body > hr:first-of-type {
    color: #DC143C;
    background-color: #DC143C;
    height: 12px;
    margin-bottom: 0px;
    border: 0;
}
img.navarrow {
    font-size: 2.5em;
    padding: 0 5px;
    text-decoration: none;
    color: #DC143C;
}

img.prevarrow:after {
    content: "🡄"
}
img.uparrow:after {
    content: "🡅"
}
img.nextarrow:after {
    content: "🡆"
}

@media (min-width: 800px) {
    div#colorbar {
        display: block;
    }
    div#main {
        grid-template-columns: 1fr 5fr 200px;
    }
    div#content {
        max-width: 600px;
    }
    div#sidebar {
        max-width: 200px;
    }
}
```

`macros.hva`:
```latex

% RESPONSIVE HTML
\let\oldmeta=\@meta
\renewcommand{\@meta}{%
\oldmeta
\begin{rawhtml}
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- TODO: schema.org, opengraph, twitter cards -->
\end{rawhtml}}

% NAVIGATION LINKS
\let\oldsetlinkstext=\setlinkstext
% \newcommand{\setlinkstext}[3]
\renewcommand{\setlinkstext}[3]{%
\begin{rawhtml}
<div class="navarrows">
\end{rawhtml}
\oldsetlinkstext{#1}{#2}{#3}
\begin{rawhtml}
</div>
\end{rawhtml}}
```

- Schema.org, OpenGraph, Twitter Cards:
  - https://github.com/CodeForAntarctica/codeforantarctica.github.io/pull/3
  - https://github.com/wrdrd/docs/blob/1e784dc779d80f18501f32d634a34bd4c6347176/docs/conf.py#L305
  - https://github.com/gcushen/hugo-academic/blob/master/layouts/partials/jsonld/article.html

`Makefile`:

- https://github.com/AllenDowney/ThinkStats2/blob/master/book/Makefile

```Makefile
# [...]

docker-build:
	uid=$(id -u) docker build -t thinkbooks:latest .

docker-run-bash:
	docker run --rm -it -v "$(shell pwd)/..":/home/app/src thinkbooks:latest /bin/bash

docker-run-hevea:
	docker run --rm -it -v "$(shell pwd)/..":/home/app/src thinkbooks:latest make -C /home/app/src/book hevea
```

`Dockerfile`:

- https://hub.docker.com/r/readthedocs/build/dockerfile

```Dockerfile
FROM readthedocs/build:latest
# https://hub.docker.com/r/readthedocs/build/dockerfile
# texlive, python2, python3, miniconda2, miniconda3

ARG uid=1000
ARG user="app"
ARG home="/home/${user}"
#ARG __wrk="${home}/-wrk"
#ARG workon_home="${__wrk}/-ve37"
#ARG workon_home="${home}/.virtualenvs"
#ARG venvname="appname"
#ARG project="${__wrk}/${venvname}"
#ARG virtual_env="${workon_home}/${venvname}"

USER root
RUN useradd ${user} -d ${home} -s /usr/bin/bash -u ${uid} -m
RUN apt-get install -y hevea && rm -rf /var/lib/apt/lists/*

USER ${uid}
VOLUME ${home}
CMD ["/bin/bash"]
```
